# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class DebugLinkAllocateHeap(p.MessageType):
    MESSAGE_WIRE_TYPE = 109

    def __init__(
        self,
        sizes: List[int] = None,
    ) -> None:
        self.sizes = sizes if sizes is not None else []

    @classmethod
    def get_fields(cls):
        return {
            1: ('sizes', p.UVarintType, p.FLAG_REPEATED),
        }
