# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .LiquidAmount import LiquidAmount
from .LiquidBlindOutput import LiquidBlindOutput

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class LiquidBlindTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 801

    def __init__(
        self,
        inputs: List[LiquidAmount] = None,
        outputs: List[LiquidBlindOutput] = None,
    ) -> None:
        self.inputs = inputs if inputs is not None else []
        self.outputs = outputs if outputs is not None else []

    @classmethod
    def get_fields(cls):
        return {
            1: ('inputs', LiquidAmount, p.FLAG_REPEATED),
            2: ('outputs', LiquidBlindOutput, p.FLAG_REPEATED),
        }
