# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class LiquidSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 807

    def __init__(
        self,
        script_sig: List[bytes] = None,
    ) -> None:
        self.script_sig = script_sig if script_sig is not None else []

    @classmethod
    def get_fields(cls):
        return {
            1: ('script_sig', p.BytesType, p.FLAG_REPEATED),
        }
