# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .LiquidAmount import LiquidAmount


class LiquidBlindOutput(p.MessageType):

    def __init__(
        self,
        amount: LiquidAmount = None,
        ecdh_pubkey: bytes = None,
        ecdh_privkey: bytes = None,
        committed_script: bytes = None,
        random_seed32: bytes = None,
    ) -> None:
        self.amount = amount
        self.ecdh_pubkey = ecdh_pubkey
        self.ecdh_privkey = ecdh_privkey
        self.committed_script = committed_script
        self.random_seed32 = random_seed32

    @classmethod
    def get_fields(cls):
        return {
            1: ('amount', LiquidAmount, 0),
            2: ('ecdh_pubkey', p.BytesType, 0),
            3: ('ecdh_privkey', p.BytesType, 0),
            4: ('committed_script', p.BytesType, 0),
            5: ('random_seed32', p.BytesType, 0),
        }
