# Automatically generated by pb2py
# fmt: off
import protobuf as p


class LiquidSignTxInput(p.MessageType):

    def __init__(
        self,
        prev_hash: bytes = None,
        prev_index: int = None,
        sequence: int = None,
        issuance: bytes = None,
        value: bytes = None,
        script_code: bytes = None,
        sign_privkey: bytes = None,
    ) -> None:
        self.prev_hash = prev_hash
        self.prev_index = prev_index
        self.sequence = sequence
        self.issuance = issuance
        self.value = value
        self.script_code = script_code
        self.sign_privkey = sign_privkey

    @classmethod
    def get_fields(cls):
        return {
            1: ('prev_hash', p.BytesType, 0),
            2: ('prev_index', p.UVarintType, 0),
            3: ('sequence', p.UVarintType, 0),
            4: ('issuance', p.BytesType, 0),
            5: ('value', p.BytesType, 0),
            6: ('script_code', p.BytesType, 0),
            7: ('sign_privkey', p.BytesType, 0),
        }
