# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class LiquidGetBlindedAddress(p.MessageType):
    MESSAGE_WIRE_TYPE = 806

    def __init__(
        self,
        address_n: List[int] = None,
        coin_name: str = None,
        script_type: int = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.coin_name = coin_name
        self.script_type = script_type

    @classmethod
    def get_fields(cls):
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('coin_name', p.UnicodeType, 0),
            3: ('script_type', p.UVarintType, 0),
        }
