# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .LiquidAmount import LiquidAmount


class LiquidUnblindedOutput(p.MessageType):
    MESSAGE_WIRE_TYPE = 804

    def __init__(
        self,
        amount: LiquidAmount = None,
    ) -> None:
        self.amount = amount

    @classmethod
    def get_fields(cls):
        return {
            1: ('amount', LiquidAmount, 0),
        }
