# Automatically generated by pb2py
# fmt: off
import protobuf as p


class LiquidAmount(p.MessageType):
    MESSAGE_WIRE_TYPE = 805

    def __init__(
        self,
        value: int = None,
        value_blind: bytes = None,
        asset: bytes = None,
        asset_blind: bytes = None,
    ) -> None:
        self.value = value
        self.value_blind = value_blind
        self.asset = asset
        self.asset_blind = asset_blind

    @classmethod
    def get_fields(cls):
        return {
            1: ('value', p.UVarintType, 0),
            2: ('value_blind', p.BytesType, 0),
            3: ('asset', p.BytesType, 0),
            4: ('asset_blind', p.BytesType, 0),
        }
