# Automatically generated by pb2py
# fmt: off
import protobuf as p


class LiquidSignTxOutput(p.MessageType):

    def __init__(
        self,
        asset: bytes = None,
        value: bytes = None,
        nonce: bytes = None,
        script_pubkey: bytes = None,
    ) -> None:
        self.asset = asset
        self.value = value
        self.nonce = nonce
        self.script_pubkey = script_pubkey

    @classmethod
    def get_fields(cls):
        return {
            1: ('asset', p.BytesType, 0),
            2: ('value', p.BytesType, 0),
            3: ('nonce', p.BytesType, 0),
            4: ('script_pubkey', p.BytesType, 0),
        }
