# Automatically generated by pb2py
# fmt: off
import protobuf as p


class TxConfidentialAsset(p.MessageType):

    def __init__(
        self,
        value: bytes = None,
        asset: bytes = None,
        nonce: bytes = None,
    ) -> None:
        self.value = value
        self.asset = asset
        self.nonce = nonce

    @classmethod
    def get_fields(cls):
        return {
            1: ('value', p.BytesType, 0),  # required
            2: ('asset', p.BytesType, 0),  # required
            3: ('nonce', p.BytesType, 0),
        }
